### ISSUE TITLE
Pillar per platform

### ISSUE THREAD

**Issue by myoung34** [saltstack/kitchen-salt#102]
Is there a way to set pillars/top per platform?

Having overall pillars works on a test of one OS, what if i want to define pillars that are different for a centos platform vs an ubuntu platform?

https://github.com/saltstack-formulas/jenkins-formula/blob/master/.kitchen.yml

for reference, how can i define pillar `netcat_pkg` for amazonlinux/centos?

**Comment by barkingfoodog** [comment]
The best way to do this is build the salt state to support multiple platforms using a `map.jinja` file. Check out the [salt docs](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#abstracting-static-defaults-into-a-lookup-table) for a write-up on how to do this.

You can then use test kitchen to test that your state works properly on each platform.

**Comment by sroegner** [comment]
@barkingfoodog understood, but for testing it would still be interesting to define platform-dependent non-default values. Is that possible?

**Comment by barkingfoodog** [comment]
Yes. To create values specific for the test you could setup platform-specific suites and use the `excludes:` directive to target each platform:
```
platforms:
  - name: centos
  - name: ubuntu
suites:
  - name: centos
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              pillar
        pillar.sls:
          netcat_pkg: centos_pkg
    excludes:
      - ubuntu
  - name: ubuntu
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              pillar
        pillar.sls:
          netcat_pkg: ubuntu_pkg
    excludes:
      - centos
```

**Comment by myoung34** [comment]
@barkingfoodog the problem there is you have to duplicate your tests

`test/integration/default` would get copied to `test/integration/ubuntu` and `test/integration/centos` with no differences between the files, meaning any tests that are added/removed/changed have to be cargo culted

**Comment by barkingfoodog** [comment]
Yes, although I would expect some tests would need vary based on the platform. I can see a couple solutions here:
1. Use conditional code in the tests to target each platform and then symlink the tests together
2. Break out a "common" test suite that tests platform-agnostic behavior. In the platform-specific suites only test the behavior that is platform-specific.

I haven't tried symlinking the test directories but I don't see why that wouldn't work.

**Comment by myoung34** [comment]
I found a way to merge pillars properly in kitchen which resolves this:

```
---
driver:
  name: docker
  use_sudo: false
  privileged: true

verifier:
  name: inspec
  format: doc

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: jenkins
  pillars:
    top.sls:
      base:
        '*':
          - jenkins
          - nginx
    jenkins.sls:
      jenkins:
        lookup:
          netcat_pkg: netcat
          java_executable: /usr/lib/java/bin/java
          jenkins_port: 8080
          port: 80
          home: /var/lib/jenkins
          user: jenkins
          group: www-data
          nginx_user: jenkins
          server_name: localhost
          master_url: http://localhost:8080
          use_upstart: False
          plugins:
            timeout: 90
            installed:
              - greenballs
          pkgs:
            - jenkins
    nginx.sls:
      nginx:
        user_auth_enabled: False
        default_user: jenkins
        webuser: jenkins
        use_upstart: False
        use_sysvinit: False
        ng:
          pid_file: /var/run/nginx.pid

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /sbin/init
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
  - name: centos-7
    driver_config:
      run_command: /sbin/init
      privileged: true
    provisioner:
      pillars:
        jenkins.sls:
          jenkins:
            lookup:
              netcat_pkg: nmap-netcat

suites:
 - name: default
   provisioner:
     vendor_path: vendor
     state_top:
       base:
         '*':
           - sun-java
           - sun-java.env
           - jenkins.plugins
           - jenkins.jobs
           - nginx
           - nginx.ng
           - nginx.ng.config
           - nginx.ng.service
           - jenkins.nginx

```
