### ISSUE TITLE
init_environment doesn't work?

### ISSUE THREAD

**Issue by kgeorgak** [saltstack/kitchen-salt#109]
Hi all,

I am trying to use encrypted pillars with kitchen-salt and I need a way to copy my keys into /tmp/kitchen/etc/salt before salt-call . Seemed that the init_environment was the way to go but it doesn't seem to work? Even test commands don't seem to run. For example something like:

```
provisioner:
  name: salt_solo
  is_file_root: true
  require_chef: false
  init_environment: |
    touch /tmp/init_environment_test
```
will not produce the file in /tmp

Looking at the code it looks like the definition of the function init_environment exists but it doesn't get called anywhere? 

Thanks in advance,
Kostas
