### ISSUE TITLE
Broken ability to fetch dependencies from path

### ISSUE THREAD

**Issue by axmetishe** [saltstack/kitchen-salt#121]
### Docs
```yaml
provisioner:
  dependencies:
    - name: foo
      path: ../formulas/foo
```
### Version
broken since 0.0.25

#### dependencies.erb:
```
  # install formulas
  config[:dependencies].select{|dependency| dependency.has_key?(:repo)}.each do |formula|
```
only dependencies with "repo" key are fetched.

#### .kitchen.yml
```yaml
provisioner:
  name: salt_solo
  formula: zabbix
  dependencies:
    - path: ../oracle-jdk-formula
      name: oracle-jdk
    - path: ../nginx-formula
      name: nginx
    - path: ../fpm-formula
      name: fpm
```
