### ISSUE TITLE
Provisioners Dependencies Attribute fails on git pulls

### ISSUE THREAD

**Issue by sjmorse** [saltstack/kitchen-salt#134]
When running the provisioner with the dependencies attribute. If you are pulling from git and the machine doesn't have git pre-installed, this fails to pull the dependency.

Example .kitchen.yml:

```
driver: 
  name: vagrant

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: foobar
  dependencies:
  - name: apache
    repo: git
    source: https://github.com/saltstack-formulas/apache-formula.git
  pillars-from-files:
    subversion.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - foobar
          - apache
  state_top:
    base:
      "*":
        - apache

platforms:
  - name: bento/centos-7.3
```
The workaround is to create a vagrantfile and add turn provisioning back on for the platform installing the dependency (git in this case). 

Doubt this ranks high but seems like a quality of life bug.
