### ISSUE TITLE
converge hangs with salt master lookups failed

### ISSUE THREAD

**Issue by alem0lars-yr** [saltstack/kitchen-salt#153]
When I run `bundle exec kitchen converge` I get a ton of errors in `/var/log/salt/minion`:

```
...
2017-09-08 06:28:12,362 [salt.utils       ][ERROR   ][14335] DNS lookup of 'salt' failed.
2017-09-08 06:28:12,363 [salt.minion      ][ERROR   ][14335] Master hostname: 'salt' not found. Retrying in 30 seconds
...
```

and the converge seems to hang.

This is the `kitchen.yml`:

```
---
driver:
  name: vagrant
  cachier: true
  network:
    - ["private_network", {ip: "192.168.56.48"}]
    - ["private_network", {ip: "192.168.56.49"}]
  synced_folders:
    - ["./tmp/kitchen-shared-data",
       "/tmp/kitchen-shared-data"]
  customize:
    nicpromisc2: allow-all
    nicpromisc3: allow-all

platforms:
  - name: ubuntu-16.04

provisioner:
  name: salt_solo
  require_chef: false
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: 2016.11.3
  state_top:
    base: 
      '*':
       - foo
       - bar
  pillars:
    top.sls:
      base:
        '*':
          - baz
  pillars-from-files:
    pillar-test.sls: pillar.example
  grains:
    foo: bar
suites:
  - name: default

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --hosts=default --ssh-config=.ssh-config --sudo test/integration/$KITCHEN_SUITE
```

How can I solve this?

Thanks
