### ISSUE TITLE
Not all states are being copied to the test-kitchen box

### ISSUE THREAD

**Issue by qgriffith-zz** [saltstack/kitchen-salt#162]
I have a directory structure like

/states/
  /java
  /mongo
  /foo-application

I am creating .kitchen.yml in the states directory. The foo-application uses the java and mongo states along with it's own states. During the kitchen verify it appears only the foo-application directory is being copied to /tmp/kitchen/srv/salt and I get an error  **Specified SLS 'java' in environment 'base' is not available on the salt master**

My kitchen file looks like
```

---
driver:
  name: vagrant
  customize:
    memory: 2048

platforms:
  - name: centos-6

provisioner:
  name: salt_solo
  formula: foo-application
  pillars:
  state_top:
    base:
      '*':
        - foo-application
        - java
        - mongo

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - foo-application
              - java
              - mongo
       foo-application.sls:
          component: foo
          env: dev
      salt_version: 2016.11.7
      salt_install: yum
      require_chef: false

verifier:
  name: shell
  command: testinfra -v --sudo --host="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}" --junit-xml "junit-${KITCHEN_INSTANCE}.xml" "test/integration/${KITCHEN_SUITE}"

```
