### ISSUE TITLE
Python code from dependent formulas not usable

### ISSUE THREAD

**Issue by dalvizu** [saltstack/kitchen-salt#195]
I'm using kitchen-salt's `salt_solo` provisioner to test out some salt code which uses dependent formulas `java` and `jenkins` from the community `salt-repos`:

* https://github.com/salt-formulas/salt-formula-java
* https://github.com/salt-formulas/salt-formula-jenkins

My `.kitchen.yml` looks like so:

```
suites:
  - name: jenkins
    provisioner:
      name: salt_solo
      dependencies:
        - name: java
          repo: git
          source: https://github.com/salt-formulas/salt-formula-java
        - name: jenkins
          repo: git
          source: https://github.com/salt-formulas/salt-formula-jenkins.git
      is_file_root: true
      salt_version: '2017.7.1'
      pillars:
        top.sls:
          base:
            '*':
              - jenkins
      pillars-from-files:
        java.sls: test/pillars/java.yml
        jenkins.sls: test/pillars/jenkins.yml
      state_top:
         base:
          '*':
            - jenkins
      inspec_tests:
        - jenkins
```

Test pillar data:

test/pillars/java.yml
```
java:
  environment:
    enabled: true
    version: '8'
    platform: openjdk
    development: true
```

test/pillars/jenkins.yml
```
jenkins:
  master:
    enabled: true
    http:
      port: 8080
      network: any
      protocol: http
    mode: EXCLUSIVE
    no_config: true
    user:
      admin:
        api_token: "foo"
        password: "super secret password"
        email: "root@localhost"
    plugins:
      - name: slack
```

This fails to provision - I see an error like so:

```
       ----------
                 ID: /var/lib/jenkins/users/admin/config.xml
           Function: file.managed
             Result: False
            Comment: Unable to manage file: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'jenkins_common.encode_password'
            Started: 18:37:57.891412
           Duration: 190.639 ms
            Changes:
```

This refers to a file jenkins_common defined in the formula here:

https://github.com/salt-formulas/salt-formula-jenkins/blob/master/_modules/jenkins_common.py

Running on latest kitchen-salt repo, dependencies in Gemfile.lock here:

```
DEPENDENCIES
  kitchen-ec2 (= 2.0.0)
  kitchen-inspec (= 0.19.0)
  kitchen-salt!
  kitchen-transport-rsync (= 0.1.2)
  kitchen-transport-sshtar (= 0.1.2)
  test-kitchen (= 1.19.2)
```

I can provide a Vagrantfile describing my test kitchen environment if it is helpful
