### ISSUE TITLE
Running `kitchen converge` twice creates a recursive symlink in formulas directory

### ISSUE THREAD

**Issue by dalvizu** [saltstack/kitchen-salt#196]
*Steps to reproduce*:
1. Use a .kitchen.yml formula listing a formula as dependency (example below)
2. Run `kitchen converge`
3. Log in with kitchen to target VM (`kitchen login`), inspect formula directory `/tmp/kitchen/srv/salt/<formula-name>/`
4. Note no symbolic link `/tmp/kitchen/srv/salt/<formula-name>/</formula-name>`
5. Run `kitchen converge` again
6. Log in with kitchen to target VM (`kitchen login`), inspect formula directory `/tmp/kitchen/srv/salt/<formula-name>/`

*Expected behavior:*
* no symbolic link `/tmp/kitchen/srv/salt/<formula-name>/</formula-name>`

*Observed behavior:*
* Symbolic link created at `/tmp/kitchen/srv/salt/<formula-name>/</formula-name>`, which links recursively to the parent directory `/tmp/kitchen/srv/salt/<formula-name>/` 

Example `.kitchen.yml`:
```
suites:
  - name: docker
    provisioner:
      name: salt_solo
      dependencies:
        - name: docker
          repo: git
          source: https://github.com/saltstack-formulas/docker-formula.git
          branch: 'master'
      is_file_root: true
      salt_version: '2017.7.1'
      pillars:
        top.sls:
          base:
            '*':
              - docker
          docker:
            version: 17.05.0*
      state_top:
        base:
          '*':
            - docker
```
