### ISSUE TITLE
Crashes if pillar_from_directories is the only pillar configuration

### ISSUE THREAD

**Issue by ipmb** [saltstack/kitchen-salt#205]
My provisioner looks like this:

```yaml
provisioner:
  name: salt_solo
  salt_version: 2016.11
  is_file_root: true
  local_salt_root: .
  state_top_from_file: true
  pillars_from_directories:
    - pillar
```

When doing the `converge`, this code block is executed: https://github.com/saltstack/kitchen-salt/blob/673b07ea8346aabec4139eb9cfc21b088a547c44/lib/kitchen-salt/pillars.rb#L32-L39

In my case, it failed because my `local_salt_root` did not have a `pillar` directory.

If I add:

```yaml
  pillars:
    fake.sls: []
```

It works as expected. I would expect everything to work if I only define `pillars_from_directories` in my provisioner.
