### ISSUE TITLE
Allow using `top.sls` pillar from file

### ISSUE THREAD

**Issue by Lirt** [saltstack/kitchen-salt#225]
Hello,

I tried to specify `top.sls` pillar from file but did not success. Let's say this is usual way people define pillars in suites or provisioner:

```yaml
provisioner:
  name: salt_solo
  formula: dns
  salt_install: bootstrap
  salt_version: 2018.3.0
  require_chef: false
  state_top:
    base:
      '*':
        - dns
suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - dns
```

Now I would like to use `top.sls` pillar from file. The code I tried is this:

```yaml
provisioner:
  name: salt_solo
  formula: dns
  salt_install: bootstrap
  salt_version: 2018.3.0
  require_chef: false
  state_top:
    base:
      '*':
        - dns
suites:
  - name: default
    provisioner:
    pillars-from-files:
      top.sls: test/integration/default/top.sls
```

This example ends with this error:

> Preparing pillars into /srv/pillar
> Failed to complete #converge action: [undefined method `each' for nil:NilClass] on default-ubuntu-1604

I tried to diagnose with `kitchen diagnose --all`, but there was nothing helpful in the log. I expected that `top.sls` file I included in `pillars-from-files` will be copied into `/srv/pillar` and everything will work well.

Please, let me know if you need more information to troubleshoot this or if this is actually not implemented or if I am using it wrong.

**Comment by gtmanfred** [comment]
seems reasonable

**Comment by daks** [comment]
I'm not sure that `pillars-from-files` can be used to generate the top.sls, but you can use it to generate a pillar sls file and then include it in your pillar top.sls, something like

```
provisioner:
  pillars:
    top.sls:
       base:
        "*":
          - dns
    
suites:
  - name: default
    provisioner:
    pillars-from-files:
      dns.sls: test/integration/default/top.sls
```

I use that here https://github.com/daks/usersandgroups-formula/blob/master/kitchen.yml and it works well.
