### ISSUE TITLE
Discrepancy in kitchen-salt docs, but/and function doesn't work anyway.

### ISSUE THREAD

**Issue by ghost** [saltstack/kitchen-salt#234]
hi,
`https://kitchen.saltstack.com/docs/file/docs/provisioner_options.md#salt_minion_config_dropin_files` reads:

```
salt_minion_config_dropin_files

default: []

Allows reading of files outside the kitchen for files to add as minion config drop-ins. The files will be numbered in order of appearance in the array and will be written to /tmp/kitchen/etc/salt/minion.d.

Example

provisioner:
  salt_minion_config_include_files:
    - ../salt-base/master.d/nodegroups.conf
    - ../sea-salt/output-config.yml

This would generate the following files :

/tmp/kitchen/etc/salt/minion.d
  |- 97-nodegroups.conf
  |- 98-output-config.yml
```

1. So, is it `salt_minion_config_dropin_files`, or is it `salt_minion_config_include_files`?
2. It doesn't work. I need to import my `nodegroups.conf` file (so it'll map grains correctly and I don't have to `kitchen.yml`ify my pillars every single time), but `/tmp/kitchen/etc/salt/minion.d/*` is never written.
  * I've tried both relative and absolute paths to my `nodegroups.conf`
  * with both `salt_minion_config_dropin_files` and `salt_minion_config_include_files`

```
$ gem list kitchen

*** LOCAL GEMS ***

kitchen-ansible (0.48.3, 0.48.1)
kitchen-inspec (0.23.1, 0.20.0)
kitchen-salt (0.1.0, 0.0.29)
kitchen-vagrant (1.3.2, 1.3.1, 1.2.1)
test-kitchen (1.21.2, 1.20.0, 1.19.2, 1.15.0)
```
`kitchen.yml` resembles:
```

driver:
  name: vagrant

provisioner:
  name: salt_solo
  reuqire_chef: false
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git stable 2017.7.4
  salt_minion_config_include_files:
    - salt/files/etc/salt/master.d/nodegroups.conf
  is_file_root: True
#  local_salt_root: /
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - kitchen.yml
    - tests
    - chefignore
  state_collection:
    - .
  pillars_from_directories:
    - ../pillar
  grains:
    environment: lab
    datacenter: xxx
    roles:
      - loadbalancer
  state_top:
    base:
      '*':
        - docker
        - nginx
        - nginx.loadbalancer.upstreams
        - nginx.loadbalancer.servers
platforms:
  - name: ubuntu-16.04
#  - name: centos-7.2

suites:
  - name: default
```

thanks for any advice in advance
