### ISSUE TITLE
kitchen converge behind http proxy

### ISSUE THREAD

**Issue by dgengtek** [saltstack/kitchen-salt#241]
# Question

How do I set http_proxy for the provisioner? During `$ kitchen converge`  I get timeouts since the docker image is unable to pull the repositories.
```

driver:
  name: docker
  hostname: some_service.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false
  http_proxy: <%= ENV['http_proxy'] || "http://proxy:3128" %>
  https_proxy: <%= ENV['https_proxy'] || "http://proxy:3128" %>

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  http_proxy: <%= ENV['http_proxy'] || "http://proxy:3128" %>
  https_proxy: <%= ENV['https_proxy'] || "http://proxy:3128" %>
  require_chef: false
  formula: some_service
  log_level: info
  state_top:
    base:
      "*":
        - some_service
  pillars:
    top.sls:
      base:
        "*":
          - some_service
  grains:
    noservices: True
  pillars_from_files:
    some_service.sls: tests/pillar/default.sls


platforms:
  - name: centos7
    driver_config:
      image: dgengtek/centos7:v1
      platform: centos


verifier:
  name: shell
  remote_exec: false
  command: pytest -v tests/integration/

suites:
  - name: default
```
