### ISSUE TITLE
state_collection not working ?

### ISSUE THREAD

**Issue by philpep** [saltstack/kitchen-salt#252]
Hi,

I don't understand how state_collection is supposed to work.

In my project I have state files (including top.sls) in `./states`, and my kitchen.yml I have:

```
---
driver:
  name: vagrant
 
platforms:
  - name: debian-9

provisioner:
  name: salt_solo
  salt_install: distrib
  state_collection: states
  
suites:
  - name: default
```
But when running `kitchen converge`, the whole current directory is sent to `/tmp/kitchen/srv/salt` instead of only the `states` directory.

```
[...]
       Transferring files to <default-debian-9>
       Install External Dependencies
       Content of /tmp/kitchen//srv/salt :
       total 432                 
       drwxr-xr-x 13 vagrant vagrant   4096 Aug 30 09:54 .                                                                
       drwxr-xr-x  3 vagrant vagrant   4096 Aug 30 09:50 ..
       drwxr-xr-x  4 vagrant vagrant   4096 Aug 30 09:52 .kitchen
       -rw-r--r--  1 vagrant vagrant    169 Aug 30 09:50 .kitchen.yml
       drwxr-xr-x 23 vagrant vagrant   4096 Aug 30 09:52 states
       local:
       ----------
                 ID: states
           Function: no.None
             Result: False
            Comment: No Top file or external nodes data matches found.
            Changes:   
       Summary for local
       ------------
       Succeeded: 0
       Failed:    1
       ------------
       Total states run:     1
       Total run time:   0.000 ms

```

How I can achieve only having the states directory copied to the host ?

**Comment by gtmanfred** [comment]
Looking at the code, apparently state_collection is just a True or False thing, and you should specify the collection_name as states.

```
---
driver:
  name: vagrant
 
platforms:
  - name: debian-9

provisioner:
  name: salt_solo
  salt_install: distrib
  state_collection: true
  collection_name: states
  
suites:
  - name: default
```

Or, you can just specify formula.

```
---
driver:
  name: vagrant
 
platforms:
  - name: debian-9

provisioner:
  name: salt_solo
  salt_install: distrib
  formula: states
  
suites:
  - name: default
```

If you just want states copied to the /srv/ directory, you need to specify `is_file_root: True` and then filter the stuff you don't want copied in using `salt_copy_filter: []` list
