### ISSUE TITLE
salt:// URL not working in kitchen-salt

### ISSUE THREAD

**Issue by finferflu** [saltstack/kitchen-salt#256]
Hi,

This is my current relevant configuration:

```yml
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  local_salt_root: .
  is_file_root: true
  state_top:
    base:
      "*":
        - repos
        - php71
```

These are the contents of `/srv/salt`:

```
       Content of /tmp/kitchen//srv/salt :
       total 4
       drwxr-xr-x. 20 vagrant vagrant 273 Sep 14 09:45 .
       drwxr-xr-x.  4 vagrant vagrant  32 Sep 14 09:45 ..
       drwxr-xr-x.  3 vagrant vagrant  35 Sep 14 09:45 php71
       drwxr-xr-x.  3 vagrant vagrant  71 Sep 14 09:45 repos
```

In my `php71/init.sls` I am referencing a file in `php71/files/php.ini` (it does exist, and it works when running Salt outside of Test Kitchen), and I get this:

```
[ERROR   ] Source file salt://php71/files/php.ini not found
```

Am I misconfiguring anything?

Thank you.

**Comment by finferflu** [comment]
Just to add more details:

```
[vagrant@default-centos-7 ~]$ cat /tmp/kitchen/etc/salt/minion
# @markup text
local: true
state_top: top.sls
root_dir: /tmp/kitchen

file_roots:
 base:
   - /tmp/kitchen/srv/salt
   - /tmp/kitchen/srv/spm/salt

pillar_roots:
 base:
   - /tmp/kitchen/srv/pillar
   - /tmp/kitchen/srv/spm/pillar
```

As per the [documentation](https://docs.saltstack.com/en/latest/ref/file_server/file_roots.html#directory-overlay), `salt://php71/files/php.ini` should reference `/tmp/kitchen/srv/salt/php71/files/php.ini`, which does exist:

```
[vagrant@default-centos-7 ~]$ ls -la /tmp/kitchen/srv/salt/php71/files/php.ini
-rwxr-xr-x. 1 vagrant vagrant 61018 Sep 14 09:56 /tmp/kitchen/srv/salt/php71/files/php.ini
```

**Comment by finferflu** [comment]
I was able to narrow down the issue. I had this in `salt/php71/init.sls`:

```
/etc/php.ini:
    file.managed:
        - name: /etc/php.ini
        - source: salt://php71/files/php.ini
        - template: jinja
        - env: {{ env }}
```

Apparently, using `env` as a variable name confuses Salt and generates that utterly misleading error. Changing the variable to `environment` fixed this issue.
