### ISSUE TITLE
Grains not being set

### ISSUE THREAD

**Issue by finferflu** [saltstack/kitchen-salt#266]
Hi,

I've followed the instructions on how to set grains [here](https://github.com/saltstack/kitchen-salt/blob/master/docs/provisioner_options.md), like so:

```
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  grains:
    roles:
      - web-uat
...
```

And I can see while converging:

```Preparing grains into /etc/salt/grains```
