### ISSUE TITLE
Grains not being set

### ISSUE THREAD

**Issue by finferflu** [saltstack/kitchen-salt#267]
Hi,

I've followed the instructions on how to set grains [here](https://github.com/saltstack/kitchen-salt/blob/master/docs/provisioner_options.md), like so:

```
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  grains:
    roles:
      - web-uat
...
```

And I can see this while converging:

```Preparing grains into /etc/salt/grains```

However, the `grains` file isn't there:

```
$ bundle exec kitchen login
Last login: Wed Nov 21 11:43:09 2018 from 10.0.2.2
[vagrant@default-centos-7 ~]$ sudo su -
Last login: Wed Nov 21 11:40:23 UTC 2018 on pts/0
[root@default-centos-7 ~]# ll /etc/salt/
total 128
-rw-r-----. 1 root root  2926 Oct  8 15:56 cloud
drwxr-xr-x. 2 root root     6 Oct  8 16:42 cloud.conf.d
drwxr-xr-x. 2 root root     6 Oct  8 16:42 cloud.deploy.d
drwxr-xr-x. 2 root root     6 Oct  8 16:42 cloud.maps.d
drwxr-xr-x. 2 root root     6 Oct  8 16:42 cloud.profiles.d
drwxr-xr-x. 2 root root     6 Oct  8 16:42 cloud.providers.d
-rw-r-----. 1 root root 51532 Oct  8 15:56 master
drwxr-xr-x. 2 root root     6 Oct  8 16:42 master.d
-rw-r-----. 1 root root 35984 Oct  8 15:56 minion
drwxr-xr-x. 2 root root     6 Oct  8 16:42 minion.d
-rw-r--r--. 1 root root    30 Nov 21 11:37 minion_id
drwxr-xr-x. 4 root root    34 Nov 21 11:36 pki
-rw-r-----. 1 root root 28162 Oct  8 15:56 proxy
drwxr-xr-x. 2 root root     6 Oct  8 16:42 proxy.d
-rw-r-----. 1 root root   344 Oct  8 15:56 roster
```

This is reflected by the fact that my config fails to converge due to missing grains. Is there anything I'm missing?

Thank you for your time!
