### ISSUE TITLE
kitchen.yml per state directory

### ISSUE THREAD

**Issue by ksalman** [saltstack/kitchen-salt#292]
How can I have kitchen.yml file per state directory, instead of the parent directory? In my salt environment, I have a bunch of states like so:
```
mysql/init.sls
ntp/init.sls
dhcpserver/init.sls
```
And I'd like to put kitchen.yml file in each of those directories, so that those states could easily be tested if they are modified in the future. If there is a accompanying kitchen.yml file _inside_ the directory, we'd just use that to test that particular state. So it would look like this
```
mysql/init.sls
mysql/kitchen.yml
ntp/init.sls
ntp/kitchen.yml
dhcpserver/init.sls
dhcpserver/kitchen.yml
```
Is this workflow not possible?

I tried, and in my kitchen.yml file I have this bit
```
state_top:
  base:
    "*":
      - init
```
But that does include other files in each state - files used for file.managed, for example, and kitchen errors out with 
```
       ----------
                 ID: /etc/mysql.conf
           Function: file.managed
             Result: False
            Comment: Source file salt://packages/mysql/mysql.conf not found in saltenv 'base'
            Started: 03:51:08.911768
           Duration: 7773.274 ms
            Changes:
```
Kitchen does appear to copy mysql.conf in /tmp/kitchen/srv/salt, but it bombs out because there no reference to it in the state_top.

The way it is expected right now, I think, is to have kitchen.yml in the parent directory. But then we'd have to modify the kitchen.yml file every time we need to test another state. 
```
kitchen.yml
mysql/init.sls
mysql/kitchen.yml
ntp/init.sls
ntp/kitchen.yml
dhcpserver/init.sls
dhcpserver/kitchen.yml
```
