### ISSUE TITLE
Allow users to set grains from .kitchen.yml

### ISSUE THREAD

**Issue by simonmcc** [saltstack/kitchen-salt#3]
Allow users to set grains in the .kitchen.yml file so that states can use the data.

For example:

I would like to specify different suites/grains in the kitchen.yml to be able to setup multiple servers to test each of the different, but it doesn't appear to copy the grains over, eg;

```
suites:
  - name: ftphserver-stage
    attributes:
      grains:
        roles:
          - ftph-server
          - v1-infrastructure
          - development
        datacenter: europe-west1-a
        provider: gce
      datacenter: europe-west1-a
      provider: gce
```

(request from lloyd.oliver@pathintel.com)
