### ISSUE TITLE
salt_minion_extra_config and salt_minion_config_dropin_files does not work as expected

### ISSUE THREAD

**Issue by vskubriev** [saltstack/kitchen-salt#314]
salt_minion_extra_config and salt_minion_config_dropin_files does not work as expected.

There is two separate issues:

1. First with layout lists from salt_minion_extra_config in final rendered file `salt_minion_extra_config/99-minion.conf`

There is no difference how to specify list (both generates wrong yaml without indents).

E.g:

```
  salt_minion_extra_config:
    log_level: trace
    use_superseded: ['module.run']
#or
  salt_minion_extra_config:
    log_level: trace
    use_superseded:
      - module.run
```

Rendered into:

```
use_superseded:
- module.run
```

2. Second issue is that kitchen creates config file in desired place `/tmp/kitchen/etc/salt/minion.d/98-enforce.conf`, but minion shouldn't load it. Minion log files does not have a line with file `98-enforce.conf` like `99-minion.conf`config from first issue:

```
2020-07-22 13:05:10,247 [salt.config      :1897][DEBUG   ][15758] Reading configuration from /tmp/kitchen/etc/salt/minion
2020-07-22 13:05:10,248 [salt.config      :2048][DEBUG   ][15758] Including configuration from '/tmp/kitchen/etc/salt/minion.d/99-minion.conf'
2020-07-22 13:05:10,249 [salt.config      :1897][DEBUG   ][15758] Reading configuration from /tmp/kitchen/etc/salt/minion.d/99-minion.conf
```

Used config section:

```
  salt_minion_config_dropin_files:
    - enforce.conf
```

It's strange of course. But it is true.

Full `provisioner` config section:

```
provisioner:
  name: salt_solo
  log_level: trace
  salt_install: bootstrap
  require_chef: false
  formula: ubuntu
  salt_copy_filter:
    - .kitchen
    - .git
    - .vagrant
  salt_minion_extra_config:
    log_level: trace
    use_superseded: ['module.run']
  salt_minion_config_dropin_files:
    - enforce.conf
  state_top:
    base:
      '*':
        - ubuntu
  pillars:
    top.sls:
      base:
        '*':
          - ubuntu
  pillars_from_files:
    ubuntu.sls: test/salt/pillar/ubuntu.pillar
verifier:
  inspec_tests:
    - path: test/integration/default
```
