### ISSUE TITLE
`locale` command on gentoo does not accept parameters

### ISSUE THREAD

**Issue by javierbertoli** [saltstack/kitchen-salt#317]
[this line](https://github.com/saltstack/kitchen-salt/blob/d0bd55c51837a26b2d6369f48d107ae8cf90239e/lib/kitchen/provisioner/install.erb#L28) causes an error on gentoo instances

```
Results in this issue when running `kitchen converge` on Gentoo:

...
       Usage: locale-gen [options] -- [localedef options]
       
       Generate locales based upon the config file /etc/locale.gen.
       
       Options:
           -k, --keep               Don't nuke existing locales
           -d, --destdir <dir>      Use locale data in specified DESTDIR tree
           -c, --config <config>    Use specified config instead of default locale.gen
           -l, --list               List all the locales to be generated
           -a, --ask                Ask before generating each locale
           -A, --all                Pretend the locale list contains all locales
           -u, --update             Only generate locales that are missing
           -G, --generate <locale>  Generate specified locale (one shot; implies -k -u)
           -j, --jobs <num>         Number of locales to generate at a time (parallel)
           -q, --quiet              Only show errors
           -V, --version            Meaningless version information
           -h, --help               Show this help cruft
       
       Localedef Options:
           By default,  is passed to localedef.
       
       For more info, see the locale-gen(1) and locale.gen(8) manpages.
       
        * Unknown option 'en_US.UTF-8'
```

How to reproduce:

* *kitchen.yml*
```yaml
# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# For help on this file's format, see https://kitchen.ci/
driver:
  name: docker
  use_sudo: false
  privileged: true

platforms:
  - name: gentoo
    driver:
      image: gentoo/stage3

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: test
  salt_copy_filter:
    - .kitchen
    - .git

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - test.sls
      pillars:
        top.sls:
          base:
            '*':
              - test.sls
```
