### ISSUE TITLE
Grains not being set

### ISSUE THREAD

**Issue by NinjaSomething** [saltstack/kitchen-salt#332]
I'm having trouble accessing my custom grains after kitchen is finished converging.  The [provisioner documentation](https://github.com/saltstack/kitchen-salt/blob/master/docs/provisioner_options.md#grains) states the following:
`This options allows grains to be set on the guest, written out to /etc/salt/grains`

In practice I am not seeing this behavior.  The grains are being written to '/tmp/kitchen/etc/salt/grains' which is not available to salt-call within the docker instance after converging.

I'm using the [TestInfra Salt class](https://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.salt.Salt) to get the grain information which informs what should be done in my pytests.  TestInfra uses salt-call inside the docker instance to return the grain data, but because the grains aren't written to /etc/salt/grains the salt-call is returning the wrong data.

```
# ls /etc/salt/grains
ls: cannot access '/etc/salt/grains': No such file or directory
```

```
# cat /tmp/kitchen/etc/salt/grains 
---
nodename: test_karbon_300_minion
productname: NeonPoint
device_type:
  make: Karbon
  model: '300'
ethernet_port_map:
  '0': enp1s0
  '1': enp7s0
  '2': enp8s0
```
```
# salt-call --local grains.item productname
local:
    ----------
    productname:
        HP Z230 SFF Workstation
```

.kitchen.yaml
```
<% @version = '3000.6' %>
driver:
  name: docker
  user_sudo: false
  privileged: true
  username: root
  forward:
    - 80

platforms:
  - name: ubuntu-18.04
    driver_config:
      run_command: /lib/systemd/systemd

suites:
  - name: salt-acumen-karbon-300
    provisioner:
      grains:
        nodename: "test_karbon_300_minion"
        productname: "NeonPoint"
        device_type:
          make: "Karbon"
          model: "300"
        ethernet_port_map:
          "0": "enp1s0"
          "1": "enp7s0"
          "2": "enp8s0"
  - name: salt-acumen-cincoze-da-1100
    provisioner:
      grains:
        nodename: "test_cincoze_da_1100_minion"
        productname: "DA-1100"
        device_type:
          make: "Cincoze"
          model: "DA-1100"
        ethernet_port_map:
          "0": "enp1s0"
          "1": "enp2s0"
  - name: salt-acumen-ec2
    provisioner:
      grains:
        nodename: "test_ec2_minion"
        manufacturer: "Amazon EC2"
        device_type:
          make: "Amazon EC2"
          model: "t3.large"
        ethernet_port_map:
          "0": "enp1s0"
          "1": "enp2s0"
provisioner:
  name: salt_solo
  sudo: false
  salt_install: bootstrap
  salt_bootstrap_options: -P stable <%= @version %>
  log_level: debug
  is_file_root: true
  state_top_from_file: true
  require_chef: false
  dependencies:
    - name: git
      repo: apt
      package: git
    - name: vim
      repo: git
      source: git://github.com/saltstack-formulas/vim-formula.git
    - name: docker
      repo: git
      source: git://github.com/saltstack-formulas/docker-formula.git
  state_copy_filter:
    - .bundle
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
  pillars_from_directories:
    - ../pillar

verifier:
  name: shell
  remote_exec: false
  command: python3 -m pytest -s -v tests/
```
