### ISSUE TITLE
Allow to specify a top.sls file

### ISSUE THREAD

**Issue by thedrow** [saltstack/kitchen-salt#5]
Instead of duplicating it, please allow to specify a top.sls file in .kitchen.yml.

**Comment by simonmcc** [comment]
I assume this is for testing state collections and not formula?  (as a formula shouldn't have a top.sls)

**Comment by thedrow** [comment]
Yup.

**Comment by simonmcc** [comment]
Looking at this now, it might get a little tricky wrt to implied paths.  What does your repo look like?

**Comment by thedrow** [comment]
Usually I have /salt/roots/ when I'm only using vagrant.

**Comment by simonmcc** [comment]
I'm about to push up v0.0.17 which will allow you to load a top.sls from a
disk, but it will still only copy the one formula down to the guest, or
copy the directory down to $collection_name, I'm not sure that's quite what
you want is it?

You want to have a .kitchen.yml in a directory that contains multiple
directories of states, and a top.sls that references those?

On 22 May 2014 21:13, Omer Katz notifications@github.com wrote:

> Usually I have /salt/roots/ when I'm only using vagrant.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/simonmcc/kitchen-salt/issues/5#issuecomment-43938210
> .

## 

Simon McCartney
E: simon@mccartney.ie
M: +44 7710 836 915

**Comment by thedrow** [comment]
Yup. Exactly.
If I don't use formulas then I don't need them.

**Comment by lloydoliver** [comment]
In my case the structure is as follows:

```
/srv/salt/state1/
/srv/salt/state2/
/srv/salt/state3/
/srv/salt/top.sls
/srv/salt/.kitchen.yml
```

Adding the "state_top_from_file: true" into either provisioner or suite still requires me to specify the formula and, as you mentioned earlier, only copies one formula/state to the test system. This isn't ideal as state1 depends on state2, which in turn depends on state3. 

Ideally I would like to have the relevant states copied to the server based off the grain/top data. For example;

.kitchen.yml

```
suites:
  - name: some-test-suite
    provisioner:
      state_top_from_file: true
      grains:
        roles:
          - role1
          - role2
```

top.sls

```
  'G@roles:role1 and G@roles:role2':
    - match: compound
    - state1
    - state2
    - state3
```

or a workaround could be to specify a number of states to copy in the .yml, I have tried this and so far it only copies the last listed item to the test system, e.g

```
provisioner:
  name: salt_solo
  data_path: ../pillar
  salt_pillar_root: data/
  salt_state_top: /srv/salt/top.sls
  formula: state1
  formula: state2
  formula: state3  <<--- at present only this gets copied to the server, the others get ignored.
```

Would either of these solutions be possible, if so, @thedrow would either of these work for you?

**Comment by thedrow** [comment]
I'd rather work with option 1 but both work for me if there is no other choice.

**Comment by simonmcc** [comment]
If we take @lloydoliver's example:

```
/srv/salt/state1/
/srv/salt/state2/
/srv/salt/state3/
/srv/salt/top.sls
/srv/salt/.kitchen.yml
```

If I add a provisioner flag (that defaults to false) called `is_file_root`, this would then copy /src/salt down to the guest, so for this example, you'd need a .kitchen.yml that looked like this

```
suites:
  - name: some-test-suite
    provisioner:
      is_file_root: true
      state_top_from_file: true
```

Then you'd effectively be able to test a pre-built file_root?  does that sound like a workable solution?
