### ISSUE TITLE
on Debian with apt installation method, apt-get update is not run, leading to package download problems

### ISSUE THREAD

**Issue by daks** [saltstack/kitchen-salt#95]
When using kitchen-salt on Debian with apt installation method, I always got error messages about missing packages.
I think it could be solved adding a step to run ```apt-get update``` before doing the salt-minion installation.

```
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://repo.saltstack.com jessie InRelease                                 
Ign http://repo.saltstack.com jessie Release.gpg                               
Get:2 http://security.debian.org jessie/updates/main Sources [190 kB]          
Ign http://httpredir.debian.org jessie InRelease                               
Get:3 http://httpredir.debian.org jessie Release.gpg [2,373 B]                 
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [352 kB]   
Ign http://repo.saltstack.com jessie Release                                   
Get:5 http://httpredir.debian.org jessie Release [148 kB]                      
Err http://repo.saltstack.com jessie/main amd64 Packages                       
         
Err http://repo.saltstack.com jessie/main amd64 Packages                       
         
Get:6 http://httpredir.debian.org jessie/main Sources [7,056 kB]
Err http://repo.saltstack.com jessie/main amd64 Packages                       
         
Err http://repo.saltstack.com jessie/main amd64 Packages                       
         
Err http://repo.saltstack.com jessie/main amd64 Packages
         404  Not Found [IP: 198.199.77.106 80]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [6,776 kB]
Fetched 14.6 MB in 6s (2,145 kB/s)                                             
       W: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/salt-latest/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 198.199.77.106 80]
       
       E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Relevant part of my .kitchen.yml 
```
provisioner:
  name: salt_solo
  salt_install: apt
  salt_version: latest
  salt_apt_repo: http://repo.saltstack.com/apt/debian/8/amd64
  salt_apt_repo_key: http://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub
```
