### ISSUE TITLE
kitchen test very slow

### ISSUE THREAD

**Issue by alem0lars-yr** [saltstack/kitchen-salt#96]
I'm using the following `.kitchen.yml`:

```
---
driver:
  name: docker
  use_sudo: false
  privileged: true

platforms:
  - name: ubuntu-16.10

provisioner:
  name: salt_solo
  salt_install: apt
  salt_bootstrap_url: https://bootstrap.saltstack.com
  formula: honey
  state_top:
    base:
      '*':
        - honey
  pillars:
    top.sls:
      base:
        '*':
          - honey

suites:
  - name: default
    provisioner:
      pillars-from-files:
        honey.sls: pillar.example

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
 ```

However every time I run `bundle exec kitchen test` **it will re-run the salt bootstrap**. It takes sooo much time.
Is it possible to cache that operation?

Thanks
